name: Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:

  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Install NPM and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'
      - name: Build client
        run: |
          npm install --prefix ./longclaw/client
          npm run build --prefix ./longclaw/client
      - name: Upload client
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: ./longclaw/core/static/core/js

      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Download client
        uses: actions/download-artifact@v4
        with:
          name: client
          path: ./longclaw/core/static/core/js
      - name: Test with tox
        run: tox
